using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Prensentation.Models;

namespace Prensentation.Controllers
{
    [ApiController]
    [Route("api/news")]
    public class NewsController : ControllerBase
    {
        private readonly ILogger<NewsController> _logger;

        public NewsController(ILogger<NewsController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Get()
        {
            var articles = new List<ArticleModel>(){
                    new ArticleModel(){ Title = "China battery giant CATL’s $5 billion Swiss listing delayed amid Beijing regulatory concerns",UrlToImage="https://d.ibtimes.com/en/full/4432407/worker-stands-outside-factory-contemporary-amperex-technology-ltd-catl-ningde.jpg", Description = "By Scott Murdoch, Julie Zhu and Kane Wu HONG KONG (Reuters) -   Chinese battery giant CATL&#039;s plan to raise at least $5 billion in Swiss global depository receipts (GDR) has been delayed as Beijing regulators raise concerns over the large scale of the off…", Content = "The worlds largest battery maker, formally known as Contemporary Amperex Technology Co (CATL), had expected to receive a green light for the listing in Zurich from the Chinese securities regulator by… [+4000 chars]" },
                    new ArticleModel(){ Title = "Tesla's Arrival Accelerates Mexico 'Nearshoring' Boom", UrlToImage="https://d.ibtimes.com/en/full/4432395/welcome-tesla-reads-billboard-mexicos-northern-city-monterrey-where-us-electric-car-maker.jpg", Description = "Tesla's arrival accelerates Mexico 'nearshoring' boom", Content = "Welcome Tesla' reads a billboard in Mexico's northern city of Monterrey, where US electric car maker plans to open a giant factoryAFP\r\nGovernor Samuel Garcia is a man in a hurry, juggling his daught… [+4707 chars]" },
                    new ArticleModel(){ Title = "Elon Musk Still Worried By ChatGPT After Its Trump Poem", Description = "Microsoft Corporation MSFT-backed OpenAI demonstrated a new version of the artificial intelligence-based chatbot ChatGPT on Tuesday, but the technology still poses a concern for Tesla and Twitter CEO Elon Musk. What Happened: Musk reacted to screenshots share…",UrlToImage="https://www.marketscreener.com/images/twitter_MS_fdblanc.png", Content = "Microsoft Corporation MSFT-backed OpenAI demonstrated a new version of the artificial intelligence-based chatbot ChatGPT on Tuesday, but the technology still poses a concern for Tesla and Twitter CEO… [+297 chars]" },
                    new ArticleModel(){ Title = "China battery giant CATL’s $5 billion Swiss listing delayed amid Beijing regulatory concerns",UrlToImage="https://d.ibtimes.com/en/full/4432407/worker-stands-outside-factory-contemporary-amperex-technology-ltd-catl-ningde.jpg", Description = "By Scott Murdoch, Julie Zhu and Kane Wu HONG KONG (Reuters) -   Chinese battery giant CATL&#039;s plan to raise at least $5 billion in Swiss global depository receipts (GDR) has been delayed as Beijing regulators raise concerns over the large scale of the off…", Content = "The worlds largest battery maker, formally known as Contemporary Amperex Technology Co (CATL), had expected to receive a green light for the listing in Zurich from the Chinese securities regulator by… [+4000 chars]" },
                    new ArticleModel(){ Title = "Tesla's Arrival Accelerates Mexico 'Nearshoring' Boom", UrlToImage="https://d.ibtimes.com/en/full/4432395/welcome-tesla-reads-billboard-mexicos-northern-city-monterrey-where-us-electric-car-maker.jpg", Description = "Tesla's arrival accelerates Mexico 'nearshoring' boom", Content = "Welcome Tesla' reads a billboard in Mexico's northern city of Monterrey, where US electric car maker plans to open a giant factoryAFP\r\nGovernor Samuel Garcia is a man in a hurry, juggling his daught… [+4707 chars]" },
                    new ArticleModel(){ Title = "Elon Musk Still Worried By ChatGPT After Its Trump Poem", Description = "Microsoft Corporation MSFT-backed OpenAI demonstrated a new version of the artificial intelligence-based chatbot ChatGPT on Tuesday, but the technology still poses a concern for Tesla and Twitter CEO Elon Musk. What Happened: Musk reacted to screenshots share…",UrlToImage="https://www.marketscreener.com/images/twitter_MS_fdblanc.png", Content = "Microsoft Corporation MSFT-backed OpenAI demonstrated a new version of the artificial intelligence-based chatbot ChatGPT on Tuesday, but the technology still poses a concern for Tesla and Twitter CEO… [+297 chars]" },
                    new ArticleModel(){ Title = "China battery giant CATL’s $5 billion Swiss listing delayed amid Beijing regulatory concerns",UrlToImage="https://d.ibtimes.com/en/full/4432407/worker-stands-outside-factory-contemporary-amperex-technology-ltd-catl-ningde.jpg", Description = "By Scott Murdoch, Julie Zhu and Kane Wu HONG KONG (Reuters) -   Chinese battery giant CATL&#039;s plan to raise at least $5 billion in Swiss global depository receipts (GDR) has been delayed as Beijing regulators raise concerns over the large scale of the off…", Content = "The worlds largest battery maker, formally known as Contemporary Amperex Technology Co (CATL), had expected to receive a green light for the listing in Zurich from the Chinese securities regulator by… [+4000 chars]" },
                    new ArticleModel(){ Title = "China battery giant CATL’s $5 billion Swiss listing delayed amid Beijing regulatory concerns",UrlToImage="https://d.ibtimes.com/en/full/4432407/worker-stands-outside-factory-contemporary-amperex-technology-ltd-catl-ningde.jpg", Description = "By Scott Murdoch, Julie Zhu and Kane Wu HONG KONG (Reuters) -   Chinese battery giant CATL&#039;s plan to raise at least $5 billion in Swiss global depository receipts (GDR) has been delayed as Beijing regulators raise concerns over the large scale of the off…", Content = "The worlds largest battery maker, formally known as Contemporary Amperex Technology Co (CATL), had expected to receive a green light for the listing in Zurich from the Chinese securities regulator by… [+4000 chars]" },
                    new ArticleModel(){ Title = "Tesla's Arrival Accelerates Mexico 'Nearshoring' Boom", UrlToImage="https://d.ibtimes.com/en/full/4432395/welcome-tesla-reads-billboard-mexicos-northern-city-monterrey-where-us-electric-car-maker.jpg", Description = "Tesla's arrival accelerates Mexico 'nearshoring' boom", Content = "Welcome Tesla' reads a billboard in Mexico's northern city of Monterrey, where US electric car maker plans to open a giant factoryAFP\r\nGovernor Samuel Garcia is a man in a hurry, juggling his daught… [+4707 chars]" },
                    new ArticleModel(){ Title = "Elon Musk Still Worried By ChatGPT After Its Trump Poem", Description = "Microsoft Corporation MSFT-backed OpenAI demonstrated a new version of the artificial intelligence-based chatbot ChatGPT on Tuesday, but the technology still poses a concern for Tesla and Twitter CEO Elon Musk. What Happened: Musk reacted to screenshots share…",UrlToImage="https://www.marketscreener.com/images/twitter_MS_fdblanc.png", Content = "Microsoft Corporation MSFT-backed OpenAI demonstrated a new version of the artificial intelligence-based chatbot ChatGPT on Tuesday, but the technology still poses a concern for Tesla and Twitter CEO… [+297 chars]" },
                    new ArticleModel(){ Title = "China battery giant CATL’s $5 billion Swiss listing delayed amid Beijing regulatory concerns",UrlToImage="https://d.ibtimes.com/en/full/4432407/worker-stands-outside-factory-contemporary-amperex-technology-ltd-catl-ningde.jpg", Description = "By Scott Murdoch, Julie Zhu and Kane Wu HONG KONG (Reuters) -   Chinese battery giant CATL&#039;s plan to raise at least $5 billion in Swiss global depository receipts (GDR) has been delayed as Beijing regulators raise concerns over the large scale of the off…", Content = "The worlds largest battery maker, formally known as Contemporary Amperex Technology Co (CATL), had expected to receive a green light for the listing in Zurich from the Chinese securities regulator by… [+4000 chars]" },
                    new ArticleModel(){ Title = "Tesla's Arrival Accelerates Mexico 'Nearshoring' Boom", UrlToImage="https://d.ibtimes.com/en/full/4432395/welcome-tesla-reads-billboard-mexicos-northern-city-monterrey-where-us-electric-car-maker.jpg", Description = "Tesla's arrival accelerates Mexico 'nearshoring' boom", Content = "Welcome Tesla' reads a billboard in Mexico's northern city of Monterrey, where US electric car maker plans to open a giant factoryAFP\r\nGovernor Samuel Garcia is a man in a hurry, juggling his daught… [+4707 chars]" },
                    new ArticleModel(){ Title = "Elon Musk Still Worried By ChatGPT After Its Trump Poem", Description = "Microsoft Corporation MSFT-backed OpenAI demonstrated a new version of the artificial intelligence-based chatbot ChatGPT on Tuesday, but the technology still poses a concern for Tesla and Twitter CEO Elon Musk. What Happened: Musk reacted to screenshots share…",UrlToImage="https://www.marketscreener.com/images/twitter_MS_fdblanc.png", Content = "Microsoft Corporation MSFT-backed OpenAI demonstrated a new version of the artificial intelligence-based chatbot ChatGPT on Tuesday, but the technology still poses a concern for Tesla and Twitter CEO… [+297 chars]" },
                    new ArticleModel(){ Title = "China battery giant CATL’s $5 billion Swiss listing delayed amid Beijing regulatory concerns",UrlToImage="https://d.ibtimes.com/en/full/4432407/worker-stands-outside-factory-contemporary-amperex-technology-ltd-catl-ningde.jpg", Description = "By Scott Murdoch, Julie Zhu and Kane Wu HONG KONG (Reuters) -   Chinese battery giant CATL&#039;s plan to raise at least $5 billion in Swiss global depository receipts (GDR) has been delayed as Beijing regulators raise concerns over the large scale of the off…", Content = "The worlds largest battery maker, formally known as Contemporary Amperex Technology Co (CATL), had expected to receive a green light for the listing in Zurich from the Chinese securities regulator by… [+4000 chars]" },                    new ArticleModel(){ Title = "China battery giant CATL’s $5 billion Swiss listing delayed amid Beijing regulatory concerns",UrlToImage="https://d.ibtimes.com/en/full/4432407/worker-stands-outside-factory-contemporary-amperex-technology-ltd-catl-ningde.jpg", Description = "By Scott Murdoch, Julie Zhu and Kane Wu HONG KONG (Reuters) -   Chinese battery giant CATL&#039;s plan to raise at least $5 billion in Swiss global depository receipts (GDR) has been delayed as Beijing regulators raise concerns over the large scale of the off…", Content = "The worlds largest battery maker, formally known as Contemporary Amperex Technology Co (CATL), had expected to receive a green light for the listing in Zurich from the Chinese securities regulator by… [+4000 chars]" },
                    new ArticleModel(){ Title = "Tesla's Arrival Accelerates Mexico 'Nearshoring' Boom", UrlToImage="https://d.ibtimes.com/en/full/4432395/welcome-tesla-reads-billboard-mexicos-northern-city-monterrey-where-us-electric-car-maker.jpg", Description = "Tesla's arrival accelerates Mexico 'nearshoring' boom", Content = "Welcome Tesla' reads a billboard in Mexico's northern city of Monterrey, where US electric car maker plans to open a giant factoryAFP\r\nGovernor Samuel Garcia is a man in a hurry, juggling his daught… [+4707 chars]" },
                    new ArticleModel(){ Title = "Elon Musk Still Worried By ChatGPT After Its Trump Poem", Description = "Microsoft Corporation MSFT-backed OpenAI demonstrated a new version of the artificial intelligence-based chatbot ChatGPT on Tuesday, but the technology still poses a concern for Tesla and Twitter CEO Elon Musk. What Happened: Musk reacted to screenshots share…",UrlToImage="https://www.marketscreener.com/images/twitter_MS_fdblanc.png", Content = "Microsoft Corporation MSFT-backed OpenAI demonstrated a new version of the artificial intelligence-based chatbot ChatGPT on Tuesday, but the technology still poses a concern for Tesla and Twitter CEO… [+297 chars]" },
                    new ArticleModel(){ Title = "China battery giant CATL’s $5 billion Swiss listing delayed amid Beijing regulatory concerns",UrlToImage="https://d.ibtimes.com/en/full/4432407/worker-stands-outside-factory-contemporary-amperex-technology-ltd-catl-ningde.jpg", Description = "By Scott Murdoch, Julie Zhu and Kane Wu HONG KONG (Reuters) -   Chinese battery giant CATL&#039;s plan to raise at least $5 billion in Swiss global depository receipts (GDR) has been delayed as Beijing regulators raise concerns over the large scale of the off…", Content = "The worlds largest battery maker, formally known as Contemporary Amperex Technology Co (CATL), had expected to receive a green light for the listing in Zurich from the Chinese securities regulator by… [+4000 chars]" },
                    new ArticleModel(){ Title = "Tesla's Arrival Accelerates Mexico 'Nearshoring' Boom", UrlToImage="https://d.ibtimes.com/en/full/4432395/welcome-tesla-reads-billboard-mexicos-northern-city-monterrey-where-us-electric-car-maker.jpg", Description = "Tesla's arrival accelerates Mexico 'nearshoring' boom", Content = "Welcome Tesla' reads a billboard in Mexico's northern city of Monterrey, where US electric car maker plans to open a giant factoryAFP\r\nGovernor Samuel Garcia is a man in a hurry, juggling his daught… [+4707 chars]" },
                    new ArticleModel(){ Title = "Elon Musk Still Worried By ChatGPT After Its Trump Poem", Description = "Microsoft Corporation MSFT-backed OpenAI demonstrated a new version of the artificial intelligence-based chatbot ChatGPT on Tuesday, but the technology still poses a concern for Tesla and Twitter CEO Elon Musk. What Happened: Musk reacted to screenshots share…",UrlToImage="https://www.marketscreener.com/images/twitter_MS_fdblanc.png", Content = "Microsoft Corporation MSFT-backed OpenAI demonstrated a new version of the artificial intelligence-based chatbot ChatGPT on Tuesday, but the technology still poses a concern for Tesla and Twitter CEO… [+297 chars]" },
                    new ArticleModel(){ Title = "China battery giant CATL’s $5 billion Swiss listing delayed amid Beijing regulatory concerns",UrlToImage="https://d.ibtimes.com/en/full/4432407/worker-stands-outside-factory-contemporary-amperex-technology-ltd-catl-ningde.jpg", Description = "By Scott Murdoch, Julie Zhu and Kane Wu HONG KONG (Reuters) -   Chinese battery giant CATL&#039;s plan to raise at least $5 billion in Swiss global depository receipts (GDR) has been delayed as Beijing regulators raise concerns over the large scale of the off…", Content = "The worlds largest battery maker, formally known as Contemporary Amperex Technology Co (CATL), had expected to receive a green light for the listing in Zurich from the Chinese securities regulator by… [+4000 chars]" },
            };

            return Ok(new { status = "OK", articles = articles });
        }

    }
}